language: python
python: 2.7
install:
  - "pip install -U pip"
  - "pip install git+https://github.com/lektor/lektor#egg=Lektor"
script:
  - "lektor build"
  - "test \"$TRAVIS_PULL_REQUEST\" == \"false\" && test \"$TRAVIS_BRANCH\" == \"master\" && lektor deploy production || exit 0"
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.cache/lektor/builds
addons:
  ssh_known_hosts: flow.srv.pocoo.org

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/f0c538cdfc9883f81e34
